// src/routes/CreateProjectDialog.svelte
<script lang="ts">
  import { createProject } from "$lib/backend-client";
  import * as AlertDialog from "$lib/components/ui/alert-dialog";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { activeProject, projects } from "$lib/stores/projects";

  let projectName = "";

  async function onCreateProject() {
    const createdProject = await createProject(projectName);
    projects.update((p) => [...p, createdProject]);
    $activeProject = createdProject.name;
    projectName = "";
    open = false;
  }

  export let open: boolean;
</script>

<AlertDialog.Root bind:open>
  <AlertDialog.Content>
    <AlertDialog.Header>
      <AlertDialog.Title>Create new project</AlertDialog.Title>
      <AlertDialog.Description>
        <Input class="w-full" type="text" placeholder="Project name" bind:value={projectName} />
      </AlertDialog.Description>
    </AlertDialog.Header>

    <AlertDialog.Footer>
      <AlertDialog.Cancel>Close</AlertDialog.Cancel>
      <Button type="submit" on:click={onCreateProject}>Create</Button>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>

// src/routes/CreateProjectDialog.tsx
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import type { Project } from "@/lib/backend-client";
import { useState, type ChangeEvent } from "react";

interface CreateProjectDialogProps {
  open: boolean;
  onDismiss: () => void;
  onCreate: (project: Project) => void;
}

function CreateProjectDialog({ open, onDismiss, onCreate }: CreateProjectDialogProps) {
  const [name, setName] = useState("");

  function handleNameChange(ev: ChangeEvent<HTMLInputElement>) {
    setName(ev.target.value);
  }

  function handleCreateProject() {
    onCreate({
      name,
    });
  }

  return (
    <Dialog open={open} onOpenChange={onDismiss}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create new project</DialogTitle>
          <DialogDescription>
            <Input
              className="w-full"
              value={name}
              placeholder="Project name"
              onChange={handleNameChange}
            />
          </DialogDescription>
        </DialogHeader>

        <DialogFooter>
          <Button onClick={onDismiss}>Close</Button>
          <Button onClick={handleCreateProject}>Create</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export { CreateProjectDialog };
