// src/routes/+page.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/tauri";
  import { onMount } from "svelte";
  import Editor from "./test/edit/Editor.svelte";
  import FileBar from "./test/edit/FileTabs.svelte";

  // close the splashscreen when the app is ready
  onMount(() => {
    invoke("close_splashscreen");
  });
</script>

<FileBar />
<div class="flex flex-auto bg-white">
  <Editor />
</div>

// src/routes/Page.tsx
import { listProjects, type Project } from "@/lib/backend-client";
import { invoke } from "@tauri-apps/api/tauri";
import { useEffect, useState } from "react";
import { Layout } from "./Layout";
import { Editor } from "./test/edit/Editor";

function Page() {
  const [activeProject, setActiveProject] = useState<Project | null>(null);

  useEffect(() => {
    Promise.all([listProjects()]).then(([projects]) => {
      setActiveProject(projects[0] ?? null);

      invoke("close_splashscreen");
    });
  }, []);

  return <Layout>{activeProject !== null && <Editor project={activeProject} />}</Layout>;
}

export { Page };
