// src/lib/components/TestList.svelte
<script lang="ts">
  import type { Test } from "$lib/backend-client";
  import Button from "$lib/components/ui/button/button.svelte";
  import { currentFile, openTestAsFile } from "$lib/stores/editor";
  import { FileJson2, Layers } from "lucide-svelte";

  export let tests: Test[] = [];
  $: tests, console.log(`tests changed in test list:`, tests);
</script>

<div>
  <ul role="list" class="max-h-50 mb-2 mt-1 overflow-auto text-left">
    {#each tests as test (test.name)}
      <li>
        <button
          class="flex items-center gap-1 text-ellipsis py-1 text-sm hover:underline"
          on:click={() => {
            openTestAsFile(test);
          }}
        >
          {#if test.kind === "Javascript"}
            <FileJson2 size="12" />
          {:else}
            <Layers size="12" />
          {/if}

          {test.name}</button
        >
      </li>
    {/each}
  </ul>
  <Button
    class="w-full"
    on:click={() => {
      currentFile.set(null);
    }}>Create test</Button
  >
</div>

// src/components/TestList.tsx
import { Button } from "@/components/ui/button";
import { atom, useSetAtom } from "jotai";
import { FileJson2, Layers } from "lucide-react";
import type { Test } from "../lib/backend-client";

const currentFile = atom<Test | null>(null);

interface TestListProps {
  tests: Test[];
}

function TestList({ tests }: TestListProps) {
  const setCurrentFile = useSetAtom(currentFile);

  // TODO: Move this to state management
  function openTestAsFile(_test: Test) {}

  return (
    <div>
      <ul role="list" className="max-h-50 mb-2 mt-1 overflow-auto text-left">
        {tests.map((test) => (
          <li key={test.name}>
            <button
              className="flex items-center gap-1 text-ellipsis py-1 text-sm hover:underline"
              onClick={() => {
                openTestAsFile(test);
              }}
            >
              {test.kind === "Javascript" ? <FileJson2 size="12" /> : <Layers size="12" />}

              {test.name}
            </button>
          </li>
        ))}
      </ul>
      <Button
        className="w-full"
        onClick={() => {
          setCurrentFile(null);
        }}
      >
        Create test
      </Button>
    </div>
  );
}

export { TestList };
